### ISSUE TITLE
Handle Invalid Cards better

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1759]
If you end up with an invalid card - it's difficult to remove and edit, often causing crashes. Users should be able to remove invalid cards so that their cube doesn't remain in a poisoned state.

**Comment by sfarina** [comment]
I came here to file this. probably doesn't come up often, but not sure how to recover.

https://cubecobra.com/cube/list/bindercube?f=coloridentity%3DG+type%3Asorcery&view=list

should be "Cultivate"

trying to click it from "Mass removal" gives the following:
```
Cannot read properties of undefined (reading 'usd')

TypeError: Cannot read properties of undefined (reading 'usd')
at g (https://cubecobra.com/js/CubeListPage.bundle.js:2:13604)
at https://cubecobra.com/js/CubeListPage.bundle.js:2:2160036
at Array.reduce (<anonymous>)
at Le (https://cubecobra.com/js/CubeListPage.bundle.js:2:2159983)
at renderWithHooks (https://unpkg.com/react-dom@16/umd/react-dom.development.js:14938:20)
at updateFunctionComponent (https://unpkg.com/react-dom@16/umd/react-dom.development.js:17169:22)
at beginWork (https://unpkg.com/react-dom@16/umd/react-dom.development.js:18745:18)
at HTMLUnknownElement.callCallback (https://unpkg.com/react-dom@16/umd/react-dom.development.js:182:16)
at Object.invokeGuardedCallbackDev (https://unpkg.com/react-dom@16/umd/react-dom.development.js:231:18)
at invokeGuardedCallback (https://unpkg.com/react-dom@16/umd/react-dom.development.js:286:33)
```

**Comment by sfarina** [comment]
Ok, it works to replace invalid card with whatever in the single Add/Remove dialog

**Comment by dekkerglen** [comment]
think this is pretty much done now
