### ISSUE TITLE
Sample hand function raise an exception

### ISSUE THREAD

**Issue by xxaby** [dekkerglen/CubeCobra#1977]
**Describe the bug**
When I want to make a sample hand the result always looks like this:
Cannot read property 'details' of undefined

TypeError: Cannot read property 'details' of undefined
at https://cubecobra.com/js/CubeDeckPage.bundle.js:2:9792430
at https://cubecobra.com/js/CubeDeckPage.bundle.js:2:9792448
at Array.map (<anonymous>)
at c (https://cubecobra.com/js/CubeDeckPage.bundle.js:2:9792270)
at renderWithHooks (https://unpkg.com/react-dom@16/umd/react-dom.development.js:14938:20)
at mountIndeterminateComponent (https://unpkg.com/react-dom@16/umd/react-dom.development.js:17617:15)
at beginWork (https://unpkg.com/react-dom@16/umd/react-dom.development.js:18731:18)
at HTMLUnknownElement.callCallback (https://unpkg.com/react-dom@16/umd/react-dom.development.js:182:16)
at Object.invokeGuardedCallbackDev (https://unpkg.com/react-dom@16/umd/react-dom.development.js:231:18)
at invokeGuardedCallback (https://unpkg.com/react-dom@16/umd/react-dom.development.js:286:33)

**To Reproduce**
1. Got to here https://cubecobra.com/cube/deck/60ba3f8f240a8210364d1194
2. click the sample hand button

**Expected behavior**
It draw 7 card and doesn't raise the errors

**Desktop (please complete the following information):**
 - OS: windows 10 19042.985
 - Browser chrome
 - Version 91.0.4472.77

**Comment by dekkerglen** [comment]
Fixed on master

**Comment by lunakv** [comment]
@dekkerglen If you closed this because of #1978 then this should be reopened. This issue is about sample hand, not sample pack.
