### ISSUE TITLE
Cannot read properties of undefined (reading 'details')

### ISSUE THREAD

**Issue by crieggalder** [dekkerglen/CubeCobra#2454]
**Describe the bug**
When I'm logged in and I hit the "List" button for my cube (https://cubecobra.com/cube/list/simple-synergy), I get the following error:

```
Cannot read properties of undefined (reading 'details')

TypeError: Cannot read properties of undefined (reading 'details')
at https://cubecobra.com/js/CubeListPage.bundle.js:2:2259292
at mountMemo (https://cdn.jsdelivr.net/npm/react-dom@16/umd/react-dom.development.js:15577:21)
at Object.useMemo (https://cdn.jsdelivr.net/npm/react-dom@16/umd/react-dom.development.js:15873:18)
at useMemo (https://cdn.jsdelivr.net/npm/react@16/umd/react.development.js:1607:23)
at Fm (https://cubecobra.com/js/CubeListPage.bundle.js:2:2259039)
at renderWithHooks (https://cdn.jsdelivr.net/npm/react-dom@16/umd/react-dom.development.js:14938:20)
at mountIndeterminateComponent (https://cdn.jsdelivr.net/npm/react-dom@16/umd/react-dom.development.js:17617:15)
at beginWork (https://cdn.jsdelivr.net/npm/react-dom@16/umd/react-dom.development.js:18731:18)
at HTMLUnknownElement.callCallback (https://cdn.jsdelivr.net/npm/react-dom@16/umd/react-dom.development.js:182:16)
at Object.invokeGuardedCallbackDev (https://cdn.jsdelivr.net/npm/react-dom@16/umd/react-dom.development.js:231:18)
```

This error does not happen when logged out.

**Smartphone (please complete the following information):**
Chrome on Mac

**Comment by dekkerglen** [comment]
fixed with cube version reconciliation
