### ISSUE TITLE
Error Displaying Cube

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#428]
On the dev server, when viewing cube list: http://162.243.163.51/cube/list/e

This error is shown:
```TypeError: /home/dekker/apps/CubeCobra/views/cube/cube_list.pug:10
    8|   input#cubeID(type='hidden', name='cubeID', value=cube_id)
    9|   input#cuberaw(type='hidden', name='cuberaw', value=cube_raw)
  > 10|   input#canEdit(type='hidden', name='canEdit', value=(user && user.id == cube.owner).toString())
    11|   input#cubeTagColors(type='hidden', name='cubeTagColors', value=JSON.stringify(cube.tag_colors))
    12|   input#hideTagColors(type='hidden', name='hideTagColors', value=(!!user && user.hide_tag_colors === true).toString())
    13|   if user && user.id == cube.owner

Cannot read property 'toString' of null
    at eval (eval at wrap (/home/dekker/apps/CubeCobra/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:282:141)
    at template (eval at wrap (/home/dekker/apps/CubeCobra/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1672:163)
    at Object.exports.renderFile (/home/dekker/apps/CubeCobra/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/home/dekker/apps/CubeCobra/node_modules/pug/lib/index.js:417:21)
    at View.exports.__express [as engine] (/home/dekker/apps/CubeCobra/node_modules/pug/lib/index.js:464:11)
    at View.render (/home/dekker/apps/CubeCobra/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/dekker/apps/CubeCobra/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/dekker/apps/CubeCobra/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/dekker/apps/CubeCobra/node_modules/express/lib/response.js:1012:7)
    at /home/dekker/apps/CubeCobra/routes/cube_routes.js:697:13
    at /home/dekker/apps/CubeCobra/routes/cube_routes.js:159:9
    at process._tickCallback (internal/process/next_tick.js:68:7)```

**Comment by phulin** [comment]
This is an issue when logged out. I fixed it in the next PR but can also submit a smaller fix if you need one

**Comment by emmett9001** [comment]
I'm also seeing the following error on List View at the above link:
```
react-dom.production.min.js:187 TypeError: Object.fromEntries is not a function
    at new t (ListView.js:33)
    at $o (react-dom.production.min.js:129)
    at yi (react-dom.production.min.js:167)
    at Zl (react-dom.production.min.js:247)
    at Hl (react-dom.production.min.js:216)
    at Bl (react-dom.production.min.js:210)
    at Rl (react-dom.production.min.js:206)
    at react-dom.production.min.js:114
    at t.unstable_runWithPriority (scheduler.production.min.js:20)
    at po (react-dom.production.min.js:113)
```

**Comment by phulin** [comment]
Oh, interesting. Object.fromEntries is not implemented in Edge. I'll figure that out.
