### ISSUE TITLE
Draft CastError: Cast to ObjectId failed

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#905]
Unclear what the issue is, but the server is crashing with this error occasionally:

```
{ CastError: Cast to ObjectId failed for value "" at path "_id" for model "Draft"                                                                           x
app >     at new CastError (/home/dekker/CubeCobra/node_modules/mongoose/lib/error/cast.js:29:11)                                                                 
app >     at ObjectId.cast (/home/dekker/CubeCobra/node_modules/mongoose/lib/schema/objectid.js:246:11)                                                           
app >     at ObjectId.SchemaType.applySetters (/home/dekker/CubeCobra/node_modules/mongoose/lib/schematype.js:969:12)                                             
app >     at ObjectId.SchemaType._castForQuery (/home/dekker/CubeCobra/node_modules/mongoose/lib/schematype.js:1383:15)                                           
app >     at ObjectId.SchemaType.castForQuery (/home/dekker/CubeCobra/node_modules/mongoose/lib/schematype.js:1373:15)                                            
app >     at ObjectId.SchemaType.castForQueryWrapper (/home/dekker/CubeCobra/node_modules/mongoose/lib/schematype.js:1352:15)                                     
app >     at cast (/home/dekker/CubeCobra/node_modules/mongoose/lib/cast.js:315:32)                                                                               
app >     at model.Query.Query.cast (/home/dekker/CubeCobra/node_modules/mongoose/lib/query.js:4644:12)                                                           
app >     at model.Query.Query._castConditions (/home/dekker/CubeCobra/node_modules/mongoose/lib/query.js:1842:10)                                                
app >     at model.Query.<anonymous> (/home/dekker/CubeCobra/node_modules/mongoose/lib/query.js:2097:8)                                                           
app >     at model.Query._wrappedThunk [as _findOne] (/home/dekker/CubeCobra/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)                           
app >     at process.nextTick (/home/dekker/CubeCobra/node_modules/kareem/index.js:369:33)                                                                        
app >     at process._tickCallback (internal/process/next_tick.js:61:11)                                                                                          
app >   message:                                                                                                                                                  
app >    'Cast to ObjectId failed for value "" at path "_id" for model "Draft"',                                                                                  
app >   name: 'CastError',                                                                                                                                        
app >   stringValue: '""',                                                                                                                                        
app >   kind: 'ObjectId',                                                                                                                                         
app >   value: '',                                                                                                                                                
app >   path: '_id',                                                                                                                                              
app >   reason: undefined,                                                                                                                                        
app >   model: Model { Draft } } 
```

**Comment by phulin** [comment]
I believe this is caused by someone hitting the `/draft/:id` route with empty ID

**Comment by dekkerglen** [comment]
that must mean we have a bad link somewhere, I imagine.

**Comment by jkentbryant** [comment]
I get this error clicking "redraft" here: https://cubecobra.com/cube/deck/5ed071550e69ce46338df24d which sends me here: https://cubecobra.com/cube/redraft/5ed071550e69ce46338df24d

**Comment by dekkerglen** [comment]
Fixed
