### ISSUE TITLE
Invalid CSRF Token

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#906]
It looks like there is a forum that is missing the csrf token, but it is unclear what the issue is
```
 ForbiddenError: invalid csrf token                                                                                                                          
at csrf (/home/dekker/CubeCobra/node_modules/csurf/index.js:112:19)                                                                                     
at Layer.handle [as handle_request] (/home/dekker/CubeCobra/node_modules/express/lib/router/layer.js:95:5)                                             
at trim_prefix (/home/dekker/CubeCobra/node_modules/express/lib/router/index.js:317:13)                                                                
at /home/dekker/CubeCobra/node_modules/express/lib/router/index.js:284:7                                                                               
at Function.process_params (/home/dekker/CubeCobra/node_modules/express/lib/router/index.js:335:12)                                                     
at next (/home/dekker/CubeCobra/node_modules/express/lib/router/index.js:275:10)                                                                        
at Function.handle (/home/dekker/CubeCobra/node_modules/express/lib/router/index.js:174:3)                                                              
at router (/home/dekker/CubeCobra/node_modules/express/lib/router/index.js:47:12)                                                                       
at Layer.handle [as handle_request] (/home/dekker/CubeCobra/node_modules/express/lib/router/layer.js:95:5)                                              
at trim_prefix (/home/dekker/CubeCobra/node_modules/express/lib/router/index.js:317:13)                                                                 
at /home/dekker/CubeCobra/node_modules/express/lib/router/index.js:284:7                                                                                
at Function.process_params (/home/dekker/CubeCobra/node_modules/express/lib/router/index.js:335:12)                                                     
at next (/home/dekker/CubeCobra/node_modules/express/lib/router/index.js:275:10)                                                                        
at SessionStrategy.strategy.pass (/home/dekker/CubeCobra/node_modules/passport/lib/middleware/authenticate.js:338:9)                                    
at SessionStrategy.authenticate (/home/dekker/CubeCobra/node_modules/passport/lib/strategies/session.js:75:10)                                          
at attempt (/home/dekker/CubeCobra/node_modules/passport/lib/middleware/authenticate.js:361:16)    
```

**Comment by dekkerglen** [comment]
Is this happening because CSRF tokens are not present (we are not using csrfFetch when we should be), or is the issue that the actual tokens are expiring? (pages are left open for several hours, or longer than whaterver the timeout is)
